### ISSUE TITLE
Webpack 3.5.5 throw ERROR in ./node_modules/tinymce/skins/lightgray/img/loader.gif

### ISSUE THREAD

**Issue by kopax** [LoicMahieu/aor-tinymce-input#4]
I am trying to build into webpack 3.5.5 this component. 

```jsx
/* eslint-disable */

import React from 'react';
import {
  Create,
  SimpleForm,
  TextInput,
} from 'admin-on-rest';
import tinymce from 'tinymce/tinymce';
// react-tinymce use global ref
window.tinymce = tinymce;

import 'tinymce/themes/modern/theme';
import 'tinymce/skins/lightgray/skin.min.css';
import TinyMCEInput from 'aor-tinymce-input/lib/index'

export const EmailCreate = (props) => (
  <Create title="Create a Email" {...props}>
    <SimpleForm>
      <TextInput source="to" />
      <TextInput source="subject" />
      <TinyMCEInput source="text" config={{ skin: false }} />
    </SimpleForm>
  </Create>
);


```

When running with webpack I have:

```
ERROR in ./node_modules/tinymce/skins/lightgray/img/loader.gif
Module build failed: Error: spawn /usr/src/app/node_modules/gifsicle/vendor/gifsicle ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/css-loader!./node_modules/tinymce/skins/lightgray/skin.min.css 6:32349-32376
 @ ./node_modules/tinymce/skins/lightgray/skin.min.css
```

There are open issues and resources related:  

- https://github.com/tinymce/tinymce/issues/2836#issuecomment-257343190
- https://www.tinymce.com/docs/advanced/usage-with-module-loaders/

I am not sure if this up to date.
I have tried a few times to configure using the tinymce.com advices but nothing worked.

Am I the only one getting this issue ?

**Comment by LoicMahieu** [comment]
I don't think the problem is webpack, tinymce or this module. The error is saying that `gifsicle` executable is not found. You certainly use a image loader that try to optimize the file and thus, try to use gifsicle.

Try to just use `file-loader` and see if the error happens.

See https://github.com/imagemin/gifsicle-bin/issues/51
